# coding=utf-8

OK = 'OK'
FAILED = 'FAILED'
UNKNOWN = 'UNKNOWN'
MANAGEMENT_IP = 'MANAGEMENT_IP'
CEPH_PUBLIC_IP = 'CEPH_PUBLIC_IP'
STORAGE_IP = 'STORAGE_IP'
PRIVATE_IP = 'PRIVATE_IP'
ROLLER_IP = 'ROLLER_IP'
IP_TYPES = (MANAGEMENT_IP, CEPH_PUBLIC_IP, STORAGE_IP, PRIVATE_IP, ROLLER_IP)
EVACUATION = 'EVACUATION'
MIGRATION = 'MIGRATION'
IPMI_POWER_OFF = 'IPMI_POWER_OFF'
